### ISSUE TITLE
Make nicer aliases like Mailcow

### ISSUE THREAD

**Issue by timwhite** [schemen/privacycow#2]
Mailcows default spam alias generator makes a nice "readable" username. The formula it uses is a "readable" word between 3 and 9 characters, followed by a `.` and then another readable word between 3 and 9 characters.

The code for a "readable" username is as follows:
```php
function readable_random_string($length = 8) {
  $string = '';
  $vowels = array('a', 'e', 'i', 'o', 'u');
  $consonants = array('b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z');
  $max = $length / 2;
  for ($i = 1; $i <= $max; $i++) {
    $string .= $consonants[rand(0,19)];
    $string .= $vowels[rand(0,4)];
  }
  return $string;
}
```

This should be fairly easy to recreate in python to be consistent.

**Comment by schemen** [comment]
Thank you for the issue and the PR, I'll have a look at it as soon as I can.

I just arrived back from an absence as well as setting up a new pc :) It should be done within the next week.

**Comment by schemen** [comment]
I have merged the PR into the main branch, thank you! I like this change. 

There was a merge conflict which I have resolved. This happened due to #1
